# Generated by Django 3.1 on 2020-08-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20200831_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='items', to='goods.Category'),
        ),
    ]
